In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0:5] = 100

In [5]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
arr = np.arange(0,11)

In [21]:
arr_2d = np.arange(5,46,5)

In [22]:
arr_2d = arr_2d.reshape(3,3)

In [23]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
arr_2d[2,1]

40

In [25]:
arr_2d[arr_2d > 20]

array([25, 30, 35, 40, 45])