## NumPy Arrays

In [1]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
myarr = np.array(mylist)

In [6]:
type(myarr)

numpy.ndarray

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(5,2)

array([[0.88908065, 0.52972103],
       [0.21002457, 0.3404523 ],
       [0.05800202, 0.60037782],
       [0.02026499, 0.18439365],
       [0.53876273, 0.29082352]])

In [26]:
np.random.randn(2,3)

array([[ 0.4484166 ,  2.02184908, -1.5010486 ],
       [-2.46412682, -0.31875335, -0.85513944]])

In [28]:
np.random.randint(0,101,(4,5))

array([[59, 61, 45, 45, 13],
       [86, 99, 90, 10, 34],
       [97, 27, 59, 98, 35],
       [ 7, 68, 17, 11, 78]])

In [30]:
arr = np.arange(0,25)

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
rnarr = np.random.randint(0,101,7)

In [33]:
rnarr.max()

97

In [34]:
rnarr.min()

13